# Generated by Django 4.1.3 on 2022-12-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
        migrations.AddField(
            model_name='user',
            name='count',
            field=models.IntegerField(default=0, help_text='Number of otp sent'),
        ),
        migrations.AddField(
            model_name='user',
            name='validated',
            field=models.BooleanField(default=False, help_text='if it is true, that means user have validate otp correctly in second API'),
        ),
    ]
