# Generated by Django 4.1.3 on 2022-12-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_phoneotp_user_count_user_validated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='timestamp',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='user',
            name='is_bank_varified',
            field=models.BooleanField(default=False, help_text='User Added his account details', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_busssiness_card',
            field=models.BooleanField(default=False, help_text='User created business card', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, help_text='Users mobile number is verfied with otp', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_user_verified',
            field=models.BooleanField(default=False, help_text='Aadhar and gst verified user', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
