# Generated by Django 4.1.3 on 2022-12-14 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_role_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ManyToManyField(blank=True, related_name='authors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_start_date', models.PositiveSmallIntegerField(blank=True, help_text='Starting year of company', null=True)),
                ('company_bio', models.TextField()),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('profile_image', models.ImageField(blank=True, default='downloads/default_profile_image.jpeg', null=True, upload_to='profile_images')),
                ('cover_images', models.ImageField(blank=True, default='downloads/default-cover.png', upload_to='cover_images')),
                ('routes', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='account.routes')),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
