# Generated by Django 4.1.3 on 2022-12-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_routes_name_remove_userprofile_routes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='company_start_date',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Starting year of company', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cover_images',
            field=models.ImageField(blank=True, default='downloads/default-cover.png', upload_to='cover_images'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='downloads/default_profile_image.jpeg', null=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='user',
            name='routes',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_routes', to='account.routes'),
        ),
    ]
