# Generated by Django 4.1.3 on 2022-12-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_company_bio_user_company_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cover_images',
            new_name='cover_image',
        ),
    ]
