# Generated by Django 4.1.3 on 2022-12-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_cover_images_user_cover_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
