# Generated by Django 4.1.3 on 2022-12-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_officeaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeaddress',
            name='pincode',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
