# Generated by Django 4.1.3 on 2022-12-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_officeaddress_pincode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_bank_varified',
            new_name='is_bank_verified',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_busssiness_card',
            new_name='is_bussiness_card',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_aadhaar_verified',
            field=models.BooleanField(default=False, help_text='User kyc,using adhaar', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_gst_verified',
            field=models.BooleanField(default=False, help_text='User kyc,using gst', max_length=20),
        ),
    ]
