# Generated by Django 4.1.3 on 2022-12-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_rename_is_bank_varified_user_is_bank_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
