# Generated by Django 4.1.3 on 2022-12-27 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_user_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='view_count',
        ),
    ]
