# Generated by Django 4.1.3 on 2022-12-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_user_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
