# Generated by Django 4.1.3 on 2022-12-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_user_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
