# Generated by Django 4.1.3 on 2022-12-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_user_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phonenumber',
            new_name='phone',
        ),
    ]
