# Generated by Django 4.1.3 on 2022-12-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_rename_phonenumber_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='contact_number',
        ),
    ]
