# Generated by Django 4.1.3 on 2022-12-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_rename_phone_user_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_number',
        ),
    ]
