# Generated by Django 4.1.3 on 2023-01-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_image',
            field=models.ImageField(blank=True, default='downloads/banner_profile_image.jpeg', null=True, upload_to='banner_images'),
        ),
    ]
