# Generated by Django 4.1.3 on 2023-01-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_user_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner_image',
            field=models.ImageField(blank=True, default='downloads/banners/lorry1.jpg', null=True, upload_to='banner_images'),
        ),
    ]
