# Generated by Django 4.1.3 on 2023-01-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_alter_user_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='banner_image',
        ),
    ]
