# Generated by Django 4.1.3 on 2023-01-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_remove_user_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qa_data', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
