# Generated by Django 4.1.3 on 2022-12-14 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Businesscard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person_name', models.CharField(max_length=30)),
                ('Designation', models.CharField(max_length=30)),
                ('Alternative_contact', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('Bussiness_Address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Vehicle_load_capacity', models.CharField(blank=True, max_length=30, null=True)),
                ('Vehicle_Type', models.CharField(blank=True, max_length=30, null=True)),
                ('Is_Tyres_defined', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=80)),
                ('drop_location', models.CharField(max_length=80)),
                ('material_name', models.CharField(max_length=70)),
                ('quantity', models.CharField(max_length=70)),
                ('excepted_price', models.CharField(max_length=80)),
                ('is_advance_pay', models.BooleanField(default=False)),
                ('to_pay', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='services.vehical')),
            ],
        ),
        migrations.CreateModel(
            name='Attachnewlorry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserVehicle_number', models.CharField(max_length=50)),
                ('Current_location', models.CharField(max_length=35)),
                ('Permit', models.CharField(max_length=50)),
                ('Is_all_permit', models.BooleanField(blank=True, null=True)),
                ('Is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('Is_Rc_verfied', models.BooleanField(blank=True, default=False, null=True)),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.vehical')),
            ],
        ),
    ]
