# Generated by Django 4.1.3 on 2022-12-19 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachnewlorry',
            old_name='Current_location',
            new_name='current_location',
        ),
        migrations.RenameField(
            model_name='attachnewlorry',
            old_name='Is_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='attachnewlorry',
            old_name='Is_all_permit',
            new_name='is_all_permit',
        ),
        migrations.RenameField(
            model_name='attachnewlorry',
            old_name='Is_Rc_verfied',
            new_name='is_rc_verfied',
        ),
        migrations.RenameField(
            model_name='attachnewlorry',
            old_name='UserVehicle_number',
            new_name='uservehicle_number',
        ),
        migrations.RenameField(
            model_name='businesscard',
            old_name='Alternative_contact',
            new_name='alternative_contact',
        ),
        migrations.RenameField(
            model_name='businesscard',
            old_name='Bussiness_Address',
            new_name='bussiness_Address',
        ),
        migrations.RenameField(
            model_name='businesscard',
            old_name='Designation',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='businesscard',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='businesscard',
            old_name='Logo',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='attachnewlorry',
            name='Vehicle',
        ),
        migrations.AddField(
            model_name='attachnewlorry',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachnewlorry',
            name='vehical_tyres',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachnewlorry',
            name='vehicle_load_capacity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attachnewlorry',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attachnewlorry',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='postload',
            name='advance_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='postload',
            name='odc_consignment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='postload',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='postload',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='postload',
            name='excepted_price',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='postload',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Vehical',
        ),
    ]
