# Generated by Django 4.1.3 on 2022-12-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_current_location_attachnewlorry_current_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('vehicle_load_capacity', models.CharField(blank=True, max_length=30, null=True)),
                ('vehicle_Type', models.CharField(blank=True, max_length=30, null=True)),
                ('is_Tyres_defined', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='attachnewlorry',
            old_name='Permit',
            new_name='permit',
        ),
    ]
