# Generated by Django 4.1.3 on 2022-12-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_vehicle_rename_permit_attachnewlorry_permit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
