# Generated by Django 4.1.3 on 2022-12-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_delete_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachnewlorry',
            name='is_lorry_status',
            field=models.CharField(default='Lorry Posted', max_length=20),
        ),
    ]
