# Generated by Django 4.1.3 on 2022-12-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_rename_is_bank_varified_user_is_bank_verified_and_more'),
        ('services', '0005_attachnewlorry_is_lorry_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachnewlorry',
            name='permit',
        ),
        migrations.AddField(
            model_name='attachnewlorry',
            name='permit',
            field=models.ManyToManyField(blank=True, null=True, related_name='permit', to='account.routes'),
        ),
    ]
