# Generated by Django 4.1.3 on 2022-12-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_attachnewlorry_permit_attachnewlorry_permit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('vehicle_load_capacity', models.CharField(blank=True, max_length=30, null=True)),
                ('vehicle_Type', models.CharField(blank=True, max_length=30, null=True)),
                ('is_Tyres_defined', models.BooleanField(default=False)),
            ],
        ),
    ]
