# Generated by Django 4.1.3 on 2022-12-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_attachnewlorry_routes_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postload',
            old_name='routes_name',
            new_name='routes',
        ),
    ]
