# Generated by Django 4.1.3 on 2022-12-27 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_rename_routes_name_postload_routes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postload',
            name='routes',
        ),
    ]
