# Generated by Django 4.1.3 on 2022-12-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_postload_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postload',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
