# Generated by Django 4.1.3 on 2022-12-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_postload_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postload',
            name='view_count',
        ),
    ]
