# Generated by Django 4.1.3 on 2022-12-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_remove_postload_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='postload',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
