# Generated by Django 4.1.3 on 2023-01-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_rename_is_active_postload_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='postload',
            name='expired',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='postload',
            name='in_progress',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
