# Generated by Django 4.1.3 on 2023-01-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_postload_expired_postload_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='postload',
            name='completed',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='postload',
            name='in_transit',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
