# Generated by Django 4.1.3 on 2023-01-04 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_rename_active_postload_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postload',
            old_name='is_active',
            new_name='is_in_active',
        ),
    ]
