# Generated by Django 4.1.3 on 2023-01-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_user',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='drop_location',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='vehicle_name',
        ),
        migrations.AddField(
            model_name='bid',
            name='PostLoad',
            field=models.ManyToManyField(blank=True, null=True, related_name='postload', to='services.postload'),
        ),
    ]
