# Generated by Django 4.1.3 on 2023-01-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_remove_bid_bid_user_remove_bid_drop_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='add_comments',
            new_name='comments',
        ),
    ]
