# Generated by Django 4.1.3 on 2023-01-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_rename_add_comments_bid_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='comments',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
