# Generated by Django 4.1.3 on 2023-01-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_alter_user_phone_number'),
        ('services', '0024_postload_routes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postload',
            name='routes',
        ),
        migrations.AddField(
            model_name='attachnewlorry',
            name='routes',
            field=models.ManyToManyField(blank=True, default=None, related_name='postload_routes', to='account.routes'),
        ),
    ]
