# Generated by Django 4.1.3 on 2023-01-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_attachnewlorry_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachnewlorry',
            name='is_deactive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
