# Generated by Django 4.1.3 on 2023-01-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_attachnewlorry_is_deactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachnewlorry',
            name='expired_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
