# Generated by Django 4.1.3 on 2023-01-12 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_remove_postload_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postload',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
