# Generated by Django 4.1.3 on 2023-01-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_postload_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postload',
            old_name='updated_date',
            new_name='expired_date',
        ),
    ]
