# Generated by Django 4.1.3 on 2023-01-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_rename_updated_date_postload_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postload',
            name='expired_hour',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
