# Generated by Django 4.1.3 on 2023-01-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_postload_expired_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachnewlorry',
            name='is_deactive',
        ),
        migrations.AddField(
            model_name='attachnewlorry',
            name='expired_hour',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attachnewlorry',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('in_progress', 'in_progress'), ('in_transit', 'in_transit'), ('completed', 'completed'), ('deactive', 'deactive'), ('expired', 'expired')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='postload',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('in_progress', 'in_progress'), ('in_transit', 'in_transit'), ('completed', 'completed'), ('deactive', 'deactive'), ('expired', 'expired')], default='active', max_length=20),
        ),
    ]
