# Generated by Django 4.1.3 on 2023-01-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_remove_attachnewlorry_is_deactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachnewlorry',
            name='fixed_price',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
