# Generated by Django 4.1.3 on 2023-01-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0035_attachnewlorry_fixed_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='Attachnewlorry',
            field=models.ManyToManyField(blank=True, null=True, related_name='attachlorry', to='services.attachnewlorry'),
        ),
    ]
