# Generated by Django 4.1.3 on 2023-01-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_alter_user_phone_number'),
        ('services', '0036_bid_attachnewlorry'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachnewlorry',
            name='role',
            field=models.ManyToManyField(blank=True, related_name='role', to='account.role'),
        ),
    ]
