# Generated by Django 4.1.3 on 2023-01-19 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0038_rename_fixed_price_attachnewlorry_enter_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='price',
            new_name='fixed_price',
        ),
    ]
