# Generated by Django 4.1.3 on 2023-01-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0039_rename_price_bid_fixed_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='postload',
            name='price',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
