# Generated by Django 4.1.3 on 2023-01-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0040_postload_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, default='downloads/banners/load1.jpg', null=True, upload_to='banner_images')),
            ],
        ),
    ]
